language: php

php:
    - 7.1
    - 7.2

services:
    - redis-server

cache:
    directories:
        - node_modules
        - vendor

before_install:
    - nvm install 8
    - npm install -g yarn

install:
    - composer install --no-interaction --prefer-dist
    - php artisan key:generate
    - yarn
    - yarn dev

script:
    - php vendor/bin/phpunit
