language: php

php:
    - 7.3

services:
    - mysql
    - redis-server

env:
    global:
        - secure: YRgUj6W569l5/RGHimVQiGpezMkrsuH9r0Z0DVkYH6ZNlNltnL9EH7vBbQ88OQS/c9arv2XOnzUXa9ziM6RFuOVi8DjZiswuUDCdCEdGurz3/ABmQ8ha4jeJgpYfOgPXqr11PPymB9LYdBMbjBGJpLdNeF/muOeatE1yM4wCAK54KxoL1M7WPvCnDEflu3RSSVNPN+ca2ZQqmyPdQs4ML39zPbHqvytgfXZprTzAkchc/b+hPT3orNN44O9iZRjBga8HPoUgmzQJ//SmmLDbSypC+I/79WuH7ldbJkcnct2HGir4ER04QNPKaKvYiOJH0hiTLegogzyI1nuu29Kc8KkthJQLPLXjmqn8IUKw4FoI6pTD6uWTAikK1c5elOgw5mDSuW2iq4bakIIo30Otom7nuqNte0EIlrt0/CjsggElKu/HSApCZvYRPXR8lY6GUNLLwjNhEnD89O9qKB5GVsy1vzoYDNFUevFyIbFzE7sk51YA1uGT/m1QoWne6CzBrSjlkElbxdtlHDZteItOuGCfSMtoYpwKBviqnIddpa75DeEMBjTIHZrkujsmlFS2EqCfLMx5Il8aw6ujMV9YGizlNuCwoGgTcCXb2k4ahhStSEGRUlgPqsiPjr6q8sHmpNK3TZV3ffsxuG3VLlQETxs7jtn6gNTPAxJuWhfys3E=
        - secure: UQMOLF+ZBkq1+BzthNzQupyg0K4g3dtWJnrmYbLNX9la3NShOI6f6hHBbw3n+7xin4YgkxXhvW4DuyHjP+srBZdSU9TOgtn6TDzIwH3M8H/4PGpvyyO0dEC/ghW8L8qMHpdmW2pe3vIATIQDv4o0Tzk+55i0vA5o23kKxT+Ho9iyhTpNKxX4ic/bb/jHVdPzCynQleWDY5bdGAQC1c6FgNsqKIQzEUfVlazah0aPg0gQV6wgO3b0+TGYMMkT2HPON0sX8dEJuTxhjiVW70/oqTULF1aV/E5TSLg/EHVop8FuDC56KXAjRaJyUIds4YSNz+/UvmN02RTyTiWKQHvxq9zPUGMKroYijZI+kmKFWLJkeYFbA5NPX0BGDXkyA+fWH56chhQviRwE9TOW7bwQKlIg5ZMza3salG+Ylf2rDiYjwiFUhKNevTSCmAOgn3wxTJumDaUQviMV1J4163d/9mW2V8CVDw2Gwc0lMSvEgoU+RN1gg9XLL4OJiNUzWF/414J5LCt0Qel+snp/BPizXtfE4H0IIhgedYq+BQNLPBz3HOWtaB9Un+VHbyo+ztbZ9sZSV0qljBR8q8S2zhWtbnbhwkRxg+wd6o/wab5utCmHjYqAuYea/KctyX1YmFfeLKR3So9V7oszYeAfY9n4yB7H+ETSTOY5eqSA8Qu+4xI=

matrix:
    fast_finish: true

cache:
    directories:
        - node_modules
        - vendor

before_install:
    - nvm install node && npm install -g yarn
    - mysql -e 'CREATE DATABASE laravel_boilerplate_test;'

install:
    - cp .env.travis .env
    - echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > auth.json
    - travis_retry composer self-update
    - travis_retry composer install -n --no-suggest
    - travis_retry composer require predis/predis
    - php artisan key:generate
    - yarn
    - yarn dev

script:
    - php vendor/bin/phpunit
